config/routes.rb
Rails.application.routes.draw do
  devise_for :users #resources for models
  resources :tickets
  resources :reviews
  resources :events
  resources :locations
  root 'home#home' #sets home page/root to home/home
  get 'contact', to: 'home#contact' #root/contact url will bring to contact page (home controller, contact method)
  post 'request_contact', to: 'home#request_contact' #so submit button (contact us) will do request_contact action
  get 'about', to: 'home#about'  #root/about url will bring to about page (home controller, about method)
  get 'resources', to: 'resources#resources'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def request_contact #method called when submit button pressed
    name = params[:name]
    email = params[:email] #form values available via params hash
    telephone = params[:telephone] #keys match field names
    message = params[:message]
    if !email.blank? && !name.blank? && !message.blank?
      ContactMailer.contact_email(email, name, telephone, message).deliver_now # Send an email
      flash[:notice] = I18n.t('home.request_contact.email_sent')
      redirect_to root_path #got back to root path (home)

    else

    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
%h1= t('.title')
%p= t('.description')
%p= t('.contact')
%p= t('.creator')

= image_tag("imo.jpeg") #image in assest/images folder
%p

app/views/home/contact.html.haml
%h1= t('.title')
%h4= t('.description')

= form_tag request_contact_path, method: 'post', :id => 'ContactForm' do   #path is where form will be submitted, RESTful method
  = label_tag :name, t('.name')                                          #label tag for field with name
  = text_field_tag :name, '', title: t('.enter_name'), size: 50          #form field of particular type
  = label_tag :email, t('.email')
  = email_field_tag :email, '', title: t('.enter_email')
  = label_tag :telephone, t('.telephone')
  = telephone_field_tag :telephone, '', title: t('.enter_telephone')
  = label_tag :message, t('.message')
  = text_field_tag :message, '', title: t('.enter_message'), size: 100
  = button_tag t('.submit'), onclick: "ValidateContactForm()"                                           #submit button for form

app/views/home/home.html.haml
%h1{id: "welcome_id"}=  t('.title')  #title and description of home page, defined in en.yml
%h4= t('.description')

%h2{id: "current", onclick: "ToggleText(this)"}=  t('.current') #when clicked text shows or hides
%p{id: "currentp"}=  t('.currentp')

%h2{id: "venues", onclick: "ToggleText(this)"}=  t('.venues')
%p{id: "venuesp"}=  t('.venuesp')


%h2{id: "accounts", onclick: "ToggleText(this)"}=  t('.accounts')
%p{id: "accountsp"}=  t('.accountsp')



%h2{id: "accessibility", onclick: "ToggleText(this)"}=  t('.accessibility')


%div{id: "accessibilityp"}
  %p=  t('.font')
  %input#smallb{onclick: "SetFontSize('90%')", type: "button", value: t('.small')}
  %input#mediumb{onclick: "SetFontSize('105%')", type: "button", value: t('.medium')}
  %input#largeb{onclick: "SetFontSize('125%')", type: "button", value: t('.large')}
  %p=  t('.colour')
  %input#normalb{onclick: "SetPageStyle('Normal')", type: "button", value: t('.light')}
  %input#darkb{onclick: "SetPageStyle('Dark')", type: "button", value: t('.dark')}
%p