config/routes.rb
Rails.application.routes.draw do
  devise_for :users #resources for models
  resources :tickets
  resources :reviews
  resources :events
  resources :locations
  root 'home#home' #sets home page/root to home/home
  get 'contact', to: 'home#contact' #root/contact url will bring to contact page (home controller, contact method)
  post 'request_contact', to: 'home#request_contact' #so submit button (contact us) will do request_contact action
  get 'about', to: 'home#about'  #root/about url will bring to about page (home controller, about method)
  get 'resources', to: 'resources#resources'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tickets, dependent: :destroy #events have many tickets which will be removed if event removed
  validates_associated :tickets #tickets of event must be valid
  belongs_to :location
  validates :name, :location, :date, :start, :end, presence: true
  validates :name, length: { maximum: 255, too_long: "can be a maximum of %{count} characters" }
  validate :date_is_possible?


  scope :ordered, -> {order('date asc')} #events ordered by date
  scope :indate, -> {where('date > ?', Time.zone.today - 3.days)} #so only display events available events and recent ones

  def date_is_possible? #cant create an event that already happened
    return if date.blank?
    if date < Time.zone.today
      errors.add(:date, 'must be possible (not in the past)')
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_location, only: [:new, :create] #every event has a location
  # GET /events
  # GET /events.json
  def index
    @events = Event.ordered.indate #uses scopes to filter events
  end


  # GET /events/new
  def new
    @event = @location.events.new #sets location of event
  end


  # POST /events
  # POST /events.json
  def create
    @event = @location.events.new(event_params) #new event with only trusted parameters

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format| #uses AJAX for live updates when event destroyed
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.js { flash[:notice] = 'Event was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :location_id, :event_type, :date, :description, :start, :end, :num_tickets, :price)
    end

    #sets location to location of event
    def set_location
      @location = Location.find_by(id: params[:location_id]) || Location.find(event_params[:location_id])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event, :html => {:id => "EventForm"} do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = "#{pluralize(@event.errors.count, "error")}"
        = I18n.t('.error')
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :location
    %p= @event.location.name
    = f.hidden_field :location_id, value: @event.location.id
  .field
    = f.label :event_type
    = f.text_field :event_type
  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :start
    = f.time_select :start
  .field
    = f.label :end
    = f.time_select :end
  .field
    = f.label :num_tickets
    = f.number_field :num_tickets
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = button_tag I18n.t('.save'), onclick: "ValidateEventForm()"

app/views/events/destroy.js.erb
$('#event_<%= @event.id %>').hide();

app/views/events/edit.html.haml
%h1= I18n.t('.eventedit')

= render 'form'

= link_to t('.show'), @event
\|
= link_to t('.back'), events_path

app/views/events/index.html.haml
%h1= I18n.t('.eventtitle')

%table
  %thead
    %tr
      %th= t('.name')
      %th= t('.location')
      %th= t('.type')
      %th= t('.date')
      %th= t('.description')
      %th= t('.start')
      %th= t('.end')
      %th= t('.tickets')
      %th= t('.price')
      %th
      %th
      %th

  %tbody
    - @events.each_with_index do |event, i|
      - row_class = ""
      - if i % 2 == 0
        - row_class = "even"
      - else
        - row_class = "odd"
      %tr
        %td{:class => "#{row_class} plain"}= event.name
        %td{:class => "#{row_class} plain"}= event.location.name
        %td{:class => "#{row_class} plain"}= event.event_type
        %td{:class => "#{row_class} plain"}= event.date
        %td{:class => "#{row_class} plain"}= event.description
        %td{:class => "#{row_class} plain"}= event.start.strftime("%I:%M%p")
        %td{:class => "#{row_class} plain"}= event.end.strftime("%I:%M%p")
        %td{:class => "#{row_class} plain"}= event.num_tickets
        %td{:class => "#{row_class} plain"}
          = '£'
          = event.price
        %td{:class => "#{row_class} plain"}= link_to t('.show'), event
        %td{:class => "#{row_class} plain"}= link_to t('.edit'), edit_event_path(event)
        %td{:class => "#{row_class} plain"}= link_to t('.destroy'), event, method: :delete, data: { confirm: I18n.t('.confirm') }


%br

= link_to I18n.t('.eventnew'), locations_path
%p
%h4= I18n.t('.styles')
%input#plainb{onclick: "SetTableStyle(t('.plain'))", type: "button", value: "Plain"}
%input#brightb{onclick: "SetTableStyle(t('.bright'))", type: "button", value: "Bright"}

app/views/events/new.html.haml
%h1= I18n.t('.eventcreate')

= render 'form'

= link_to t('.back'), locations_path

app/views/events/show.html.haml
%p
  %b= t('.name')
  = @event.name
%p
  %b= t('.location')
  = @event.location.name
%p
  %b= t('.type')
  = @event.event_type
%p
  %b= t('.date')
  = @event.date
%p
  %b= t('.description')
  = @event.description
%p
  %b= t('.start')
  = @event.start.strftime("%I:%M%p")
%p
  %b= t('.end')
  = @event.end.strftime("%I:%M%p")
%p
  %b= t('.tickets')
  = @event.num_tickets
%p
  %b= t('.price')
  = '£'
  = @event.price

%b= I18n.t('.tickettitle')
%table
  %tbody
    - @event.tickets.each_with_index do |ticket, i|
      - row_class = ""
      - if i % 2 == 0
        - row_class = "even"
      - else
        - row_class = "odd"
      - if ticket.user == current_user
        %tr{id: "ticket_#{ticket.id}"}
          %td{:class => "#{row_class} plain"}= ticket.first_name
          %td{:class => "#{row_class} plain"}= ticket.last_name
          %td{:class => "#{row_class} plain"}= link_to t('.show'), ticket
          %td{:class => "#{row_class} plain"}= link_to t('.edit'), edit_ticket_path(ticket)
          %td{:class => "#{row_class} plain"}= link_to t('.destroy'), ticket, :method => :delete, :data => { :confirm => 'Are you sure? This will remove all associated tickets!' }, :remote => true

%p= link_to t('.book_ticket'), new_ticket_path(event_id: @event)

= link_to t('.edit'), edit_event_path(@event)
\|
= link_to t('.back'), events_path