config/routes.rb
Rails.application.routes.draw do
  devise_for :users #resources for models
  resources :tickets
  resources :reviews
  resources :events
  resources :locations
  root 'home#home' #sets home page/root to home/home
  get 'contact', to: 'home#contact' #root/contact url will bring to contact page (home controller, contact method)
  post 'request_contact', to: 'home#request_contact' #so submit button (contact us) will do request_contact action
  get 'about', to: 'home#about'  #root/about url will bring to about page (home controller, about method)
  get 'resources', to: 'resources#resources'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/resources.html.haml
%h1=  t('.title')  #title and description of resources page, defined in en.yml


%h2{id: "locations", onclick: "ToggleText(this)"}=  I18n.t('.locationtitle')
%div{id: "locationsp"}
  = link_to t('.pvenues'), locations_path
  %br= link_to t('.avenues'), new_location_path
  %table
    %thead
      %tr
        %th=  t('.lname')
        %th=  t('.ldescription')
        %th=  t('.country')
        %th=  t('.street')
        %th=  t('.postcode')
        %th
        %th
        %th

    %tbody
      - @locations.each_with_index do |location, i|
        - row_class = ""
        - if i % 2 == 0
          - row_class = "even"
        - else
          - row_class = "odd"
        %tr
          %td{:class => "#{row_class} plain"}= location.name
          %td{:class => "#{row_class} plain"}= location.description
          %td{:class => "#{row_class} plain"}= location.country
          %td{:class => "#{row_class} plain"}= location.street
          %td{:class => "#{row_class} plain"}= location.postcode
          %td{:class => "#{row_class} plain"}= link_to t('.show'), location
          %td{:class => "#{row_class} plain"}= link_to t('.edit'), edit_location_path(location)
          %td{:class => "#{row_class} plain"}= link_to t('.destroy'), location, method: :delete, data: { confirm: I18n.t('.confirm') }

%h2{id: "events", onclick: "ToggleText(this)"}=  t('.events')
%div{id: "eventsp"}
  = link_to t('.pevents'), events_path
  %table
    %thead
      %tr
        %th=  t('.ename')
        %th=  t('.location')
        %th=  t('.type')
        %th=  t('.date')
        %th=  t('.edescription')
        %th=  t('.start')
        %th=  t('.end')
        %th=  t('.price')
        %th=  t('.tickets')
        %th
        %th
        %th

    %tbody
      - @events.each_with_index do |event, i|
        - row_class = ""
        - if i % 2 == 0
          - row_class = "even"
        - else
          - row_class = "odd"
        %tr
          %td{:class => "#{row_class} plain"}= event.name
          %td{:class => "#{row_class} plain"}= event.location.name
          %td{:class => "#{row_class} plain"}= event.event_type
          %td{:class => "#{row_class} plain"}= event.date
          %td{:class => "#{row_class} plain"}= event.description
          %td{:class => "#{row_class} plain"}= event.start.strftime("%I:%M%p")
          %td{:class => "#{row_class} plain"}= event.end.strftime("%I:%M%p")
          %td{:class => "#{row_class} plain"}= event.num_tickets
          %td{:class => "#{row_class} plain"}
            = '£'
            = event.price
          %td{:class => "#{row_class} plain"}= link_to t('.show'), event
          %td{:class => "#{row_class} plain"}= link_to t('.edit'), edit_event_path(event)
          %td{:class => "#{row_class} plain"}= link_to t('.destroy'), event, method: :delete, data: { confirm: I18n.t('.confirm') }



%h2{id: "reviews", onclick: "ToggleText(this)"}= I18n.t('.reviewtitle')
%div{id: "reviewsp"}
  = link_to t('.vreviews'), reviews_path

%h2{id: "tickets", onclick: "ToggleText(this)"}= I18n.t('.tickettitle')
%div{id: "ticketsp"}
  = link_to t('.vtickets'), tickets_path

%br