config/routes.rb
Rails.application.routes.draw do
  devise_for :users #resources for models
  resources :tickets
  resources :reviews
  resources :events
  resources :locations
  root 'home#home' #sets home page/root to home/home
  get 'contact', to: 'home#contact' #root/contact url will bring to contact page (home controller, contact method)
  post 'request_contact', to: 'home#request_contact' #so submit button (contact us) will do request_contact action
  get 'about', to: 'home#about'  #root/about url will bring to about page (home controller, about method)
  get 'resources', to: 'resources#resources'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :events, dependent: :destroy #locations have many events which will be removed if location removed
  has_many :reviews, dependent: :destroy #locations have many reviews which will be removed if location removed
  validates_associated :reviews #reviews of location must be valid, not events since might go out of date but not be removed
  validates :name, :country, :street, :postcode, presence: true
  validates :name, uniqueness: true, length: { maximum: 255, too_long: "can be a maximum of %{count} characters" }
  validates :country, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }

  scope :ordered, -> {order('name asc')} #ordered by name
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.ordered #uses scopes to filter locaions
  end

  # GET /locations/new
  def new
    @location = Location.new
  end


  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params) #new location with only trusted parameters

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:name, :description, :country, :street, :postcode)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
= form_for @location, :html => {:id => "LocationForm"} do |f|
  - if @location.errors.any?
    #error_explanation
      %h2
        = "#{pluralize(@location.errors.count, "error")}"
        = I18n.t('.error')
      %ul
        - @location.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :street
    = f.text_field :street
  .field
    = f.label :postcode
    = f.text_field :postcode
  .actions
    = button_tag I18n.t('.save'), onclick: "ValidateLocationForm()"

app/views/locations/edit.html.haml
%h1= I18n.t('.locationedit')

= render 'form'

= link_to t('.show'), @location
\|
= link_to t('.back'), locations_path

app/views/locations/index.html.haml
%h1= I18n.t('.locationtitle')

%table
  %thead
    %tr
      %th= t('.name')
      %th= t('.description')
      %th= t('.country')
      %th= t('.street')
      %th= t('.postcode')
      %th
      %th
      %th

  %tbody
    - @locations.each_with_index do |location, i|
      - row_class = ""
      - if i % 2 == 0
        - row_class = "even"
      - else
        - row_class = "odd"
      %tr
        %td{:class => "#{row_class} plain"}= location.name
        %td{:class => "#{row_class} plain"}= location.description
        %td{:class => "#{row_class} plain"}= location.country
        %td{:class => "#{row_class} plain"}= location.street
        %td{:class => "#{row_class} plain"}= location.postcode
        %td{:class => "#{row_class} plain"}= link_to 'Show', location
        %td{:class => "#{row_class} plain"}= link_to 'Edit', edit_location_path(location)
        %td{:class => "#{row_class} plain"}= link_to 'Destroy', location, method: :delete, data: { confirm: I18n.t('.confirm') }

%br

= link_to I18n.t('.locationnew'), new_location_path
%p
%h4= I18n.t('.styles')
%input#plainb{onclick: "SetTableStyle(t('.plain'))", type: "button", value: "Plain"}
%input#brightb{onclick: "SetTableStyle(t('.bright'))", type: "button", value: "Bright"}

app/views/locations/new.html.haml
%h1= I18n.t('.locationcreate')

= render 'form'

= link_to t('.back'), locations_path

app/views/locations/show.html.haml
%p
  %b= t('.name')
  = @location.name
%p
  %b= t('.description')
  = @location.description
%p
  %b= t('.country')
  = @location.country
%p
  %b= t('.street')
  = @location.street
%p
  %b= t('.postcode')
  = @location.postcode

%b= t('.events')
%table
  %tbody
    - @location.events.each_with_index do |event, i|
      - row_class = ""
      - if i % 2 == 0
        - row_class = "even"
      - else
        - row_class = "odd"
      %tr{id: "event_#{event.id}"}
        %td{:class => "#{row_class} plain"}= event.name
        %td{:class => "#{row_class} plain"}= link_to t('.show'), event
        %td{:class => "#{row_class} plain"}= link_to t('.edit'), edit_event_path(event)
        %td{:class => "#{row_class} plain"}= link_to t('.destroy'), event, :method => :delete, :data => { :confirm => 'Are you sure? This will remove all associated reviews and events!' }, :remote => true

%p= link_to t('.add_event'), new_event_path(location_id: @location)

%b= t('.reviews')
%table
  %tbody
    - @location.reviews.each_with_index do |review, i|
      - row_class = ""
      - if i % 2 == 0
        - row_class = "even"
      - else
        - row_class = "odd"
      %tr{id: "review_#{review.id}"}
        %td{:class => "#{row_class} plain"}= review.user.email
        %td{:class => "#{row_class} plain"}
          - (1..review.rating).each do |i|
            %i.fa.fa-fw.fa-star
        - if review.user == current_user
          %td{:class => "#{row_class} plain"}= link_to t('.show'), review
          %td{:class => "#{row_class} plain"}= link_to t('.edit'), edit_review_path(review)
          %td{:class => "#{row_class} plain"}= link_to t('.destroy'), review, :method => :delete, :data => { :confirm => 'Are you sure?' }, :remote => true
        - else
          %td{:class => "#{row_class} plain"}
          %td{:class => "#{row_class} plain"}
          %td{:class => "#{row_class} plain"}



%p= link_to t('.add_review'), new_review_path(location_id: @location)

= link_to t('.edit'), edit_location_path(@location)
\|
= link_to t('.back'), locations_path